name: test_minibatch_reading_speed # workflow name
# workflow
on: [push] # 触发条件 触发workflow

jobs: # 一个workflow可以有多个jobs
  test_minibatch_job: # test_minibatch_job 第一个（目前只有一个）job，job的名字
    strategy:
      matrix:
        runner: [amax, linux02, win , win-zsp] # 12相同，xh zsp 不同

    runs-on: ${{matrix.runner}} # 指定在哪个runner上运行这个job，runner一个服务器

    steps: # 一个job里是有多个step，step会被顺序的执行, 打包了一堆要执行的东西，最顶层的包是workflow
      # workflow是被触发的单位， workflow下面有jobs，这些jobs，由github去调度分发给不同的runner执行
      # job里就是一个完整的要测试的东西
      # 默认情况下，这些job之间是独立的，可并行的
      # 一个job里包含要顺序执行的若干代码，可以理解为bash的多行代码
      # step= [step1, step2 ,step3]
      # 在yaml的语法中 - 就代表这在数组里，是某一个元素
      # step = []
    - uses: actions/checkout@v4 # step1 ref 引用了一个已经预定义好的执行单元，做为我们的step1
      #  checkout@4： 把当前分支的最新代码checkout到runner服务器中

#    - run: | # step2 ls -la 可以看一下当前目录有什么 # realpath . 可以看当前目录的真实路径是什么
#        ls -la
#        realpath .

    - name: Set up Python 3.10.19  # step3 # cache缓存加速，每当要配置python和各种依赖包时，默认是要
    #从网络下载的，每次都下载会很慢
    # 打开缓存可以让下次执行时直接从本地缓存安装
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.19'
        cache: 'pip'
        cache-dependency-path: './requirements.txt'
    # 缓存依赖的path
    # requirements.txt里只需要有直接依赖，间接依赖会被自动解析，也会使用缓存

    - name: install packages # step4 安装依赖
      run: |
        pip install -r requirements.txt

    - name: Testing... # step 5 执行这一行，
      run: |
#        python tests/test_single_process.py
        python Package/python-version-scAtlasAnalysis/test/multi_process/single_process.py
#        E:\python\scAtlas\Package\python-version-scAtlasAnalysis\test\multi_process\single_process.py